language: php

notifications:
  email: false
  
php:
  - '5.5'
  - '5.6'
  - '7.0'
  
services:
  - mysql
  
env:
  global:
    - CI_HOME=`pwd`
  matrix:
    - CODEIGNITER_VERSION="3.1.2"
  
before_install:
  - mkdir ${CI_HOME}/testing_base && mv !(testing_base) ${CI_HOME}/testing_base
  - composer require satooshi/php-coveralls:dev-master
  - curl -o CI-${CODEIGNITER_VERSION}.zip https://codeload.github.com/bcit-ci/CodeIgniter/zip/${CODEIGNITER_VERSION}
  - unzip -qq CI-${CODEIGNITER_VERSION}.zip
  - rm -f CI-${CODEIGNITER_VERSION}.zip
  - cd CodeIgniter-${CODEIGNITER_VERSION}
  - composer require "kenjis/ci-phpunit-test:dev-master"
  - php vendor/kenjis/ci-phpunit-test/install.php -s
  - rm -f application/tests/controllers/Welcome_test.php
  - cp -R ${CI_HOME}/testing_base/* ${CI_HOME}/CodeIgniter-${CODEIGNITER_VERSION}/application/
  - ls -R ${CI_HOME}/CodeIgniter-${CODEIGNITER_VERSION}/application/tests/models
  - cd ${CI_HOME}/CodeIgniter-${CODEIGNITER_VERSION}/application/tests
  
before_script: 
  - mysql -e 'create database aauth_test;'

script: 
  - phpunit --coverage-clover ${CI_HOME}/build/logs/clover.xml
  - sed -i 's/\//\/CodeIgniter-${CODEIGNITER_VERSION}\/application\//' ${CI_HOME}/build/logs/clover.xml
  - cd ${CI_HOME} && travis_retry php ${CI_HOME}/vendor/bin/coveralls -v
