language: php

php:
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

global:
  - CI=true
  - CI_ENVIRONMENT=testing

# Recommended by Travis support
sudo: required
dist: trusty
group: edge

services:
  - memcached
  - mysql

script:
  - php vendor/bin/phpunit -v

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS aauth_test;" -uroot;
  - mysql -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'aauth_test';" -uroot

before_script:
  - echo 'extension = memcached.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - shopt -s extglob dotglob && mkdir aauth_temp && mv !(aauth_temp) aauth_temp
  - git clone https://github.com/codeigniter4/CodeIgniter4.git CodeIgniter4 -b v4.0.0-alpha.4
  - cp -r aauth_temp/* CodeIgniter4 && cd CodeIgniter4 && cp _travis/env .env
  - composer install --prefer-source
